### ISSUE TITLE
What specific methods are used in target-aware part of the code and is there any reference to this method?

### ISSUE THREAD

**Issue by AshleyCry** [johnny12150/NISER#3]
I didn't find the description of the target-aware part of the code in the original article, but this part can really improve the effect of the model. Could you please tell me what specific methods are used in this part and is there any reference to this method? If so, I want to read it and further study it. Thank you very much.
![image](https://user-images.githubusercontent.com/50860756/134927302-9aa48eea-535f-48f8-94ed-08a957454f72.png)

**Comment by johnny12150** [comment]
> https://arxiv.org/abs/2005.02844

Is the modification from TA-GNN.
